# Generated by Django 4.1.7 on 2023-04-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order_validated',
            field=models.BooleanField(default=False),
        ),
    ]
