# Generated by Django 4.1.7 on 2023-04-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='town',
            options={'verbose_name': 'Ville'},
        ),
        migrations.RemoveField(
            model_name='concert',
            name='ticket',
        ),
        migrations.AddField(
            model_name='concert',
            name='ticket',
            field=models.ManyToManyField(to='store.ticket'),
        ),
    ]
