# Generated by Django 4.1.7 on 2023-04-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_town_artist_slug_concert_slug_ticket_order_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='concerts'),
            preserve_default=False,
        ),
    ]
