# Generated by Django 4.1.7 on 2023-04-10 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_ticket_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_validated',
        ),
    ]
