# Generated by Django 4.1.7 on 2023-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopper',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
