# Generated by Django 4.1.7 on 2023-04-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shopper_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopper',
            name='is_email_verified',
        ),
    ]
